### ISSUE TITLE
System.IO.FileLoadException on dotnet 5

### ISSUE THREAD

**Issue by Guyiming** [Fody/MethodDecorator#395]
I write a simple ConsoleApp, here is the code:
```
public class Person
{
        
        public string Name { get; set; }
        public int Age { get; set; }

        [Interceptor]
        public string GetName()
        {
            return Name;
        }
}

    [AttributeUsage(AttributeTargets.Property|AttributeTargets.Method)]
    public class InterceptorAttribute : Attribute, IMethodDecorator
    {
        // instance, method and args can be captured here and stored in attribute instance fields
        // for future usage in OnEntry/OnExit/OnException
        public void Init(object instance, MethodBase method, object[] args)
        {
            Console.WriteLine(string.Format("Init: {0} [{1}]", method.DeclaringType.FullName + "." + method.Name, args.Length));
        }

        public void OnEntry()
        {
            Console.WriteLine("OnEntry");
        }

        public void OnExit()
        {
            Console.WriteLine("OnExit");
        }

        public void OnException(Exception exception)
        {
            Console.WriteLine(string.Format("OnException: {0}: {1}", exception.GetType(), exception.Message));
        }
    }
```
here is the main method:
```
static void Main(string[] args)
 {
            var p = new Person { Name = "AA", Age = 1 };
            
            Console.WriteLine(p.GetName());
            Console.Read();
}
```
When I hit "F5" to start debug, it show this error:
```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'MethodDecorator, Version=1.1.1.0, Culture=neutral, PublicKeyToken=0de10386fb6c39dd'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  Source=MethodDecorator
  StackTrace:
   at MethodDecorator.Person.GetName() in E:\MyProgram\SomePractice\Fody\MethodDecorator\Person.cs:line 21
   at MethodDecorator.Program.Main(String[] args) in E:\MyProgram\SomePractice\Fody\MethodDecorator\Program.cs:line 11
```

I have tried switch "Any CPU" to "x64" or "x86", doesn't work too.

**Comment by SimonCropp** [comment]
please read the issue template
