### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by csuzw** [Fody/MethodDecorator#57]
I've forked the project (but not made any changes yet) and am trying to run the tests.  I get the following error when trying to run any test:

```
Test Name:	MethodDecoratorEx.Fody.Tests.DecoratingConstructors.ShouldReportOnEntryAndException
Test FullName:	MethodDecoratorEx.Fody.Tests.DecoratingConstructors.ShouldReportOnEntryAndException
Test Source:	F:\Git\MethodDecorator\MethodDecorator.Fody.Tests\DecoratingConstructors.cs : line 19
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at MethodDecoratorEx.Fody.Tests.SimpleTestBase..ctor()
   at MethodDecoratorEx.Fody.Tests.DecoratingConstructors..ctor()
----- Inner Stack Trace -----
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in C:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 1122
   at WeaverHelper.Weave() in F:\Git\MethodDecorator\MethodDecorator.Fody.Tests\Helpers\WeaverHelper.cs:line 54
   at MethodDecoratorEx.Fody.Tests.SimpleTestBase.CreateAssembly() in F:\Git\MethodDecorator\MethodDecorator.Fody.Tests\SimpleTestBase.cs:line 24
   at MethodDecoratorEx.Fody.Tests.SimpleTestBase..cctor() in F:\Git\MethodDecorator\MethodDecorator.Fody.Tests\SimpleTestBase.cs:line 8
Result Message:	
System.TypeInitializationException : The type initializer for 'MethodDecoratorEx.Fody.Tests.SimpleTestBase' threw an exception.
---- System.IO.IOException : The process cannot access the file 'F:\Git\MethodDecorator\TestAssemblies\SimpleTest\bin\Debug\SimpleTest2.dll' because it is being used by another process.
```

It looks like I'm not the only one with problems running the tests given the comments in the open pull request.  Is there something I am missing in regards to getting them to run or do they just not work any more?

(if it helps I'm using VS2015 update 3 on Windows Server 2012 R2)

**Comment by sstronin** [comment]
I believe I fixed this, [here](https://github.com/sstronin/MethodDecorator/commit/0d7391dc853f696f76a046aaab0a10aa67977b11). There was an attempt to re-weave the assembly for external decoration tests.

**Comment by icnocop** [comment]
I created appveyor.yml as part of https://github.com/Fody/MethodDecorator/pull/64. The pull request also fixes the failing tests.
