### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by gabrieligbastos** [Fody/MethodDecorator#62]
Is it possible to use it with .NET Core support? Tried all packages, event MethodDecorator.Fody.PP. 
Even tried to pull current version locally, changed everything to netstandard2.0, added dependency to Fody.Cecil >2.00, it compiles, but when referencing my project to the new one .NET Standard 2.0 Library, it thorws error of 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'MethodDecorator.Fody.dll' or one of its dependencies. The system cannot find the path specified.
Type:
System.IO.FileNotFoundException
StackTrace:
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at AssemblyVersionReader.GetAssemblyVersion(String path)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at AddinFinder.FindAddinAssembly(String packageName)
   at Processor.FindAssemblyPath(String weaverName)
   at Processor.ProcessConfig(WeaverEntry weaverConfig)
   at Processor.ConfigureWhenWeaversFound()
   at Processor.FindWeavers()
   at Processor.Inner()
   at Processor.Execute()
Source:
mscorlib
TargetSite:
System.Reflection.AssemblyName nGetFileInformation(System.String)
The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
Type:
System.IO.DirectoryNotFoundException
	Thrust.SCooB.Commons		1	
```

All otther packages gave me the error, that the package is out of dated and that i needed to reference Mono.Cecil 0.10 at least inside the package for Mono.Cecil v2 or higher.

How to proceed to weaver an .NET Core project?

**Comment by Annoyingselect2issue** [comment]
Install Fody
Install MethodDecorator.Fody
Install MethodDecorator.Fody.PP
Uninstall MethodDecorator.Fody

That's how Im able to get it to build and debug but then when stepping through the code the Interceptors never fire/nothing ever goes to OnEntry/Exit methods - I've been searching for a working Unit test for Fody/MethodDecorator but nothing works

**Comment by icnocop** [comment]
I've fixed issues with failing tests in https://github.com/Fody/MethodDecorator/pull/64
